---
title: "Paper Manuscript"
shorttitle: "Paper"
abstract: An Abstract
keywords: [keyword1, keyword2]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/chicago-parenthetical.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

In the 2023 [National Health Interview Survey](https://nhis.ipums.org/nhis/), survey questions attempting to capture a rough frequency of experienced discrimination and instances of practiced vigilance, in addition to the PHQ2 screener questions, were asked to American adults, nationwide. With this data, this paper seeks to answer the questions, how do discrimination and perceived threat affect the depression screener (PHQ-2) result and do discrimination and perceived threat account for depression in minority populations? 

Social determinates of health reduce health risk to inclusion in demographic categories. This paper seeks to quantitatively complicate understanding of social determinates of health through 2023 NHIS data on discrimination and heightened vigilence in relation to depression screener (PHQ-2) results. With this, shifting causal understandings of social determinates of health from inclusion in demographic category to a more complex understanding including experienced discrimination and percieved threat implicitly shifts the stigma away from the individual.

# Data and Methods

The data used in this paper were extracted from the [National Health Interview Survey](https://nhis.ipums.org/nhis/), via IPUMS Health Survey.
The data were usually conducted in-person, at 2,500 residences in each geographically clustered areas,
for a representative sample of the United States. The data were conducted year-round, with a nationally representative sample
collected monthly. The data were self-reported by the participants. Additionally, the data are generalizable to the
national level after correcting for aspects of research design, including the strata and PSUs.

# Results

# Conclusions
